'use strict';
const params=new URLSearchParams(location.hash.slice(1));
if(params.has('token'))sessionStorage.setItem('review-token',params.get('token'));
history.replaceState(null,'',location.pathname);
const token=sessionStorage.getItem('review-token')||'';
const $=id=>document.getElementById(id);let state,selected,editing;
function node(tag,text){const n=document.createElement(tag);if(text!=null)n.textContent=text;return n;}
function link(url,label){const a=node('a',label);const u=new URL(url);if(!['https:','http:'].includes(u.protocol))return node('span',label);a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';return a;}
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:{'X-Review-Token':token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const value=await response.json();if(!response.ok)throw Error(value.message||value.error);return value;}
async function guarded(work){try{await work();}catch(error){$('message').textContent=error.message;}}
async function reload(){state=await api('/api/state');$('metrics').textContent=`공개 사례 ${state.metrics.entries} · 점검 기록 ${state.metrics.attempted} · 승인 이력 ${state.metrics.approved_reviews} · 후보 대기 ${state.metrics.pending_candidates} · 최장 대기 ${state.metrics.oldest_wait_days}일`;renderEntries();renderDrafts();renderCandidates();}
function renderEntries(){const query=$('query').value.trim();const batch=$('batch').value;$('entries').replaceChildren();for(const e of state.entries.filter(e=>(!query||[e.name,e.region_id,e.category].join(' ').includes(query))&&(batch!=='pilot'||state.pilot_ids.includes(e.id))&&(batch!=='attempted'||state.attempts[e.id]))){const b=node('button',`${e.name} · ${e.region_id}`);b.onclick=()=>select(e);$('entries').append(b);}}
function select(e){editing=null;selected=e;$('new-fields').hidden=true;$('entry-heading').textContent=e.name;$('evidence').replaceChildren();$('before').textContent=JSON.stringify({scope:e.scope,operational_status:e.operational_status,review:e.review,attempt:state.attempts[e.id]},null,2);for(const url of (e.source.match(/https?:\/\/[^\s;,)\]]+/g)||[]))$('evidence').append(link(url,'기존 근거 열기 ↗'),node('br'));const f=$('review-form');f.hidden=false;f.reset();f.elements.checked.value=new Date().toISOString().slice(0,10);f.elements.status.value=e.operational_status;renderDrafts();}
$('review-form').onsubmit=event=>{event.preventDefault();guarded(async()=>{const f=event.target.elements;const checked=f.checked.value;const next=new Date(`${checked}T00:00:00Z`);next.setUTCDate(next.getUTCDate()+(f.status.value==='ended'?365:90));const draft={entry_id:selected.id,prior_sha256:state.hashes[selected.id]??null,...(selected.isNew?{new_entry:JSON.parse(f.newEntry.value)}:{}),changes:{...JSON.parse(f.changes.value),operational_status:f.status.value},reason:f.reason.value,checked_at:checked,next_review_at:next.toISOString().slice(0,10),status_supported:f.supported.checked,evidence:f.url.value?[{url:f.url.value,summary:f.summary.value,sha256:f.sha.value,publisher_id:f.publisher.value,official:true},...(editing?.evidence?.slice(1)||[])]:[]};await api('/api/command',{action:'save',command_id:crypto.randomUUID(),draft_id:editing?.id??`review-${crypto.randomUUID()}`,version:editing?.version??0,draft});$('message').textContent='변경안을 저장했습니다. 아래에서 변경 내용을 확인한 뒤 승인하세요.';await reload();});};
function renderDrafts(){$('drafts').replaceChildren();for(const d of state.drafts.filter(d=>selected&&d.entry_id===selected.id)){const article=node('article');article.append(node('h3',`${d.entry_id} · ${d.status}`),node('pre',JSON.stringify(d,null,2)));if(d.status==='draft'){const edit=node('button','변경안 수정');edit.onclick=()=>{const e=state.entries.find(e=>e.id===d.entry_id);select(e||{id:d.entry_id,name:d.new_entry?.name||d.entry_id,source:'',operational_status:'needs_review'});editing=d;selected.isNew=Boolean(d.new_entry);const f=$('review-form').elements;f.reason.value=d.reason;f.checked.value=d.checked_at;f.status.value=d.changes.operational_status||selected.operational_status;f.changes.value=JSON.stringify(d.changes,null,2);f.supported.checked=d.status_supported;if(d.new_entry){$('new-fields').hidden=false;f.newEntry.value=JSON.stringify(d.new_entry,null,2);}if(d.evidence.length){const ev=d.evidence[0];f.url.value=ev.url;f.publisher.value=ev.publisher_id;f.sha.value=ev.sha256;f.summary.value=ev.summary;}};article.append(edit);const label=node('label');const check=node('input');check.type='checkbox';label.append(check,document.createTextNode('원문과 변경안을 직접 확인했으며 이 내용의 공개를 승인합니다.'));const b=node('button','승인');b.onclick=()=>guarded(async()=>{if(!check.checked)throw Error('직접 확인한 후 승인 확인란을 선택하세요.');await api('/api/command',{action:'approve',command_id:crypto.randomUUID(),draft_id:d.id,version:d.version,human_confirmed:true});await reload();$('message').textContent='승인했습니다. 출판 미리보기 내보내기 후 Git 검토·배포 절차를 진행하세요.';});article.append(label,b);}$('drafts').append(article);}}
function renderCandidates(){$('candidates').replaceChildren();for(const c of state.candidates.filter(c=>c.status==='needs_review')){const a=node('article');a.append(node('h3',c.id),link(c.canonical_url,'후보 원문 ↗'));if(c.event_sha256)a.append(node('small',`사건 중복 제안: ${c.event_sha256.slice(0,12)} (자동 병합 아님)`));const follow=node('button','연결된 공식 근거 찾기');follow.onclick=()=>guarded(async()=>{const r=await api('/api/followup',{url:c.canonical_url});const box=node('div');box.append(node('p',r.status==='suggested'?'공식 출처 후보 — 내용 확인 필요':'연결된 공식 근거를 확보하지 못했습니다. 책임 기관 게시판을 직접 확인하세요.'));for(const s of r.suggestions)if(s.url)box.append(link(s.url,'공식 근거 후보 ↗'),node('small',s.result));a.append(box);});a.append(follow);const entry=node('input');entry.placeholder='연결할 공개 사례 ID';entry.setAttribute('aria-label',`${c.id} 연결 사례 ID`);const reason=node('select');reason.setAttribute('aria-label',`${c.id} 판정 이유`);for(const [v,t] of Object.entries({MANUAL_REVIEW:'추가 확인 필요',OFFICIAL_EVIDENCE:'공식 근거 확인',SAME_EVENT:'동일 사건',OUT_OF_SCOPE:'범위 밖',NO_OFFICIAL_EVIDENCE:'공식 근거 부족'})){const o=node('option',t);o.value=v;reason.append(o);}a.append(entry,reason);for(const [decision,label]of Object.entries({accepted:'채택',duplicate:'중복',rejected:'제외',needs_review:'보류'})){const b=node('button',label);b.onclick=()=>guarded(async()=>{await api('/api/command',{action:'candidate',command_id:crypto.randomUUID(),candidate_id:c.id,version:c.version,decision,entry_id:entry.value||null,reason_code:reason.value});await reload();});a.append(b);}$('candidates').append(a);}}
$('refresh').onclick=()=>guarded(reload);$('query').oninput=renderEntries;$('batch').onchange=renderEntries;$('export').onclick=()=>guarded(async()=>{const r=await api('/api/export',{});$('message').textContent=`검토용 파일 생성: ${r.path} (아직 공개되지 않음)`;});guarded(reload);

$('new-entry').onclick=()=>{select({id:`entry-${crypto.randomUUID()}`,name:'신규 사례',source:'',operational_status:'needs_review'});selected.isNew=true;$('new-fields').hidden=false;$('review-form').elements.newEntry.value=JSON.stringify({name:'',region_id:state.entries[0].region_id,category:state.entries[0].category,resource_type:'school',operator:'',year:new Date().getFullYear(),school_level:'고등학교',scope:'regional'},null,2);};
$('inspect-url').onclick=()=>guarded(async()=>{const f=$('review-form').elements;const r=await api('/api/inspect',{url:f.url.value});if(r.result!=='FETCHED_UNVERIFIED')throw Error('링크 점검 실패. 원문을 직접 확인하세요.');f.sha.value=r.sha256;f.url.value=r.url;$('message').textContent='문서 해시를 가져왔습니다. 공식 기관 여부와 내용은 원문에서 직접 확인하세요.';});
